// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBimjnAn9lHBckAm0D-NW64-flXaEG8bgk',
    appId: '1:373687789939:web:9b408bc707507edcc2bd06',
    messagingSenderId: '373687789939',
    projectId: 'abdurasulsapp',
    authDomain: 'abdurasulsapp.firebaseapp.com',
    storageBucket: 'abdurasulsapp.appspot.com',
    measurementId: 'G-B19EXFJY73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVq4N2z0OzvmPExSUi7Hxi0QfSer6ptRU',
    appId: '1:373687789939:android:c9455fbf8d3d51fec2bd06',
    messagingSenderId: '373687789939',
    projectId: 'abdurasulsapp',
    storageBucket: 'abdurasulsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdyGnwvgp8-IjhhTYvfdB1E9N2bColKFI',
    appId: '1:373687789939:ios:9d49793ec2e2dca7c2bd06',
    messagingSenderId: '373687789939',
    projectId: 'abdurasulsapp',
    storageBucket: 'abdurasulsapp.appspot.com',
    androidClientId: '373687789939-348og7ftnil9et6rsdenhq479f3g9f8v.apps.googleusercontent.com',
    iosBundleId: 'com.najottalim.firebaseAppNajot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdyGnwvgp8-IjhhTYvfdB1E9N2bColKFI',
    appId: '1:373687789939:ios:b8790e7d1512eb9dc2bd06',
    messagingSenderId: '373687789939',
    projectId: 'abdurasulsapp',
    storageBucket: 'abdurasulsapp.appspot.com',
    androidClientId: '373687789939-348og7ftnil9et6rsdenhq479f3g9f8v.apps.googleusercontent.com',
    iosBundleId: 'com.najottalim.firebaseAppNajot.RunnerTests',
  );
}
